#include "core/LfsService.h"
#include <QProcess>
#include <QTemporaryDir>
#include <QtTest>

class TestLfsService : public QObject {
    Q_OBJECT
private slots:
    void parsesTrackedPatterns()
    {
        const QByteArray attributes =
            "# generated by git lfs\n"
            "*.psd filter=lfs diff=lfs merge=lfs -text\n"
            "docs/** -text\n"
            "\"large files/*.bin\" filter=lfs diff=lfs merge=lfs -text\n"
            "*.psd filter=lfs diff=lfs merge=lfs -text\n";
        QCOMPARE(Git::LfsService::parseAttributes(attributes),
                 QStringList({QStringLiteral("*.psd"),
                              QStringLiteral("large files/*.bin")}));
    }

    void parsesLocks()
    {
        const QByteArray json = R"({"locks":[
            {"id":"11","path":"art/hero.psd","locked_at":"2026-07-17T01:02:03Z","owner":{"name":"Alice"},"ours":true},
            {"id":"12","path":"video/intro.mov","owner":{"name":"Bob"}}
        ]})";
        QString error;
        const auto locks = Git::LfsService::parseLocks(json, &error);
        QVERIFY2(error.isEmpty(), qPrintable(error));
        QCOMPARE(locks.size(), 2);
        QCOMPARE(locks.at(0).path, QStringLiteral("art/hero.psd"));
        QCOMPARE(locks.at(0).owner, QStringLiteral("Alice"));
        QVERIFY(locks.at(0).ownedByCurrentUser);
        QVERIFY(!locks.at(1).ownedByCurrentUser);
    }

    void rejectsInvalidLocks()
    {
        QString error;
        QVERIFY(Git::LfsService::parseLocks("not-json", &error).isEmpty());
        QVERIFY(!error.isEmpty());
    }

    void tracksAndUntracksWhenLfsIsInstalled()
    {
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        QProcess git;
        git.setWorkingDirectory(directory.path());
        git.start(QStringLiteral("git"), {QStringLiteral("init")});
        QVERIFY(git.waitForFinished(10000));
        QCOMPARE(git.exitCode(), 0);

        Git::LfsService service(directory.path());
        QString error;
        if (!service.state(false, &error).installed)
            QSKIP(qPrintable(error));
        QVERIFY2(service.track(QStringLiteral("*.bin"), &error), qPrintable(error));
        QVERIFY(service.state(false, &error).trackedPatterns.contains(
            QStringLiteral("*.bin")));
        QVERIFY2(service.untrack(QStringLiteral("*.bin"), &error), qPrintable(error));
        QVERIFY(!service.state(false, &error).trackedPatterns.contains(
            QStringLiteral("*.bin")));
    }
};

QTEST_GUILESS_MAIN(TestLfsService)
#include "TestLfsService.moc"
